baseURL = "http://drumato.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "My New Hugo Site"

theme = "DoIt"
[author]
  name = "Drumato"

[params]
  # DoIt theme version
  version = "0.2.X"
  [params.app]
    title = "drumato.com"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  # Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # recently updated posts settings
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10

  [params.header]
    [params.header.title]
      name = "drumato.com"
      typeit = true 
  [params.page]
    [params.page.header]
      # whether to enable auto header numbering
      # 是否开启标题自动编号
      [params.page.header.number]
        enable = true
        [params.page.header.number.format]
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
    [params.page.toc]
      enable = true
      keepStatic = false 
      auto = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false 
      Pinterest = false
      Tumblr = false
      HackerNews = true 
      Reddit = true  
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket =true  
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    # DoIt CHANGED | 0.2.0 Comment config
    [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia", "fuse")
    type = "fuse"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # DoIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # DoIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

[languages]
  [languages.en]
    weight = 1
    title = "drumato.com"
    languageCode = "en"
    languageName = "English"
    [languages.en.params.home.posts]
      enable = false
    [languages.en.params.home.profile]
      enable = true
      title = "Drumato"
      subtitle = "A software engineer loves 🍑"
      avatarURL = "/images/drumato.png"
      typeit = true
      social = true
    [[languages.en.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Post"
      url = "/posts/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "diaries"
      pre = ""
      post = ""
      name = "Diary"
      url = "/diaries/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "thissite"
      pre = ""
      post = ""
      name = "This Site"
      url = "/thissite/"
      title = ""
      weight = 4

  [languages.ja]
    weight = 2
    title = "drumato.com"
    # language code, CN only here
    languageCode = "ja"
    languageName = "Japanese"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true
    [languages.ja.params.home.posts]
      enable = false
    [languages.ja.params.home.profile]
      enable = true
      title = "Drumato"
      subtitle = "A software engineer loves 🍑"
      avatarURL = "/images/drumato.png"
      typeit = true
      social = true
    [[languages.ja.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 1
    [[languages.ja.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "記事一覧"
      url = "/posts/"
      title = ""
      weight = 2
    [[languages.ja.menu.main]]
      identifier = "diaries"
      pre = ""
      post = ""
      name = "日記一覧"
      url = "/diaries/"
      title = ""
      weight = 3
    [[languages.ja.menu.main]]
      identifier = "thissite"
      pre = ""
      post = ""
      name = "このサイトについて"
      url = "/thissite/"
      title = ""
      weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  # DoIt CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

# Options for taxonomies
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

