baseURL = "http://drumato.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "drumato.com"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

[params]
  # DoIt theme version
  version = "0.2.X"
[params.page]
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = true
  # configure the link to view source the post
  linkToSource = "https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/{path}"
  # "https://github.com/user/repo/blob/main/{path}"
  # configure the link to edit the post
  linkToEdit = "https://github.com/HEIGE-PCloud/DoIt/edit/main/exampleSite/content/{path}"
  # https://github.com/user/repo/edit/main/{path}
  # https://gitlab.com/user/repo/-/edit/main/{path}
  # https://bitbucket.org/user/repo/src/main/{path}?mode=edit
  # configure the link to report issue for the post
  linkToReport = "https://github.com/HEIGE-PCloud/DoIt/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/{path}|"
  # https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
  # https://gitlab.com/user/repo/-/issues/new?issue[title]=[bug]%20{title}&issue[description]=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://gitlab.com/user/repo/-/edit/main/{path}|
  # whether to show the full text content in RSS
  rssFullText = false
  # Page style ("normal", "wide")
  pageStyle = "normal"
  # whether to enable series navigation
  seriesNavigation = true
  # Display a message at the beginning of an article to warn the reader that its content might be outdated.

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # DoIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # DoIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

[languages]
  [languages.en]
    weight = 1
    title = "drumato.com"
    languageCode = "en"
    languageName = "English"
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "diaries"
      pre = ""
      post = ""
      name = "Diaries"
      url = "/diaries/"
      title = ""
      weight = 2
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 3

  [languages.ja]
    weight = 2
    title = "drumato.com"
    # language code, CN only here
    languageCode = "ja"
    languageName = "Japanese"
    hasCJKLanguage = true
    [[languages.ja.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "記事一覧"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.ja.menu.main]]
      identifier = "diaries"
      pre = ""
      post = ""
      name = "日記一覧"
      url = "/diaries/"
      title = ""
      weight = 2
    [[languages.ja.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "タグ"
      url = "/tags/"
      title = ""
      weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
